import type { Lead } from '@/types'

export const MOCK_LEADS: Lead[] = [
  {
    id: 'mock-place-1',
    place_id: 'mock-place-1',
    name: 'Pizzaria Bella Napoli Moema',
    category: 'Pizzaria',
    categories: ['restaurant', 'pizza_restaurant', 'food'],
    address: 'Av. Moema, 452 - Moema, São Paulo - SP, 04077-021',
    lat: -23.6041,
    lng: -46.6623,
    phone: '(11) 98765-4321',
    phone_e164: '+5511987654321',
    is_mobile: true,
    has_whatsapp: true,
    has_site: false,
    has_social_only: false,
    rating: 4.8,
    reviews_count: 245,
    business_status: 'OPERATIONAL',
    status: 'OPERATIONAL',
    price_level: 2,
    has_photos: true,
    score: 95,
    funil_status: 'novo',
    google_maps_uri: 'https://maps.google.com/?cid=123456789',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-place-2',
    place_id: 'mock-place-2',
    name: 'Dr. Roberto Silva Odontologia Integrada',
    category: 'Dentista',
    categories: ['dentist', 'health', 'doctor'],
    address: 'R. Pedro de Toledo, 780 - Vila Mariana, São Paulo - SP',
    lat: -23.5976,
    lng: -46.6432,
    phone: '(11) 99123-8899',
    phone_e164: '+5511991238899',
    is_mobile: true,
    has_whatsapp: true,
    has_site: false,
    has_social_only: true,
    website: 'https://instagram.com/drrobertosilva',
    rating: 4.9,
    reviews_count: 88,
    business_status: 'OPERATIONAL',
    status: 'OPERATIONAL',
    price_level: 3,
    has_photos: true,
    score: 90,
    funil_status: 'novo',
    google_maps_uri: 'https://maps.google.com/?cid=987654321',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-place-3',
    place_id: 'mock-place-3',
    name: 'Espaço VIP Barber & Hair',
    category: 'Salão de Beleza',
    categories: ['hair_care', 'beauty_salon', 'barber_shop'],
    address: 'Al. dos Maracatins, 1120 - Moema, São Paulo - SP',
    lat: -23.6087,
    lng: -46.6578,
    phone: '(11) 97456-1122',
    phone_e164: '+5511974561122',
    is_mobile: true,
    has_whatsapp: true,
    has_site: false,
    has_social_only: false,
    rating: 4.7,
    reviews_count: 114,
    business_status: 'OPERATIONAL',
    status: 'OPERATIONAL',
    has_photos: true,
    score: 85,
    funil_status: 'novo',
    google_maps_uri: 'https://maps.google.com/?cid=456789123',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-place-4',
    place_id: 'mock-place-4',
    name: 'Pet Shop & Clínica Veterinária Amigo Fiel',
    category: 'Pet Shop',
    categories: ['veterinary_care', 'pet_store'],
    address: 'Av. Ibirapuera, 2200 - Indianópolis, São Paulo - SP',
    lat: -23.6012,
    lng: -46.6589,
    phone: '(11) 96321-4455',
    phone_e164: '+5511963214455',
    is_mobile: true,
    has_whatsapp: true,
    has_site: false,
    has_social_only: false,
    rating: 4.6,
    reviews_count: 62,
    business_status: 'OPERATIONAL',
    status: 'OPERATIONAL',
    has_photos: true,
    score: 80,
    funil_status: 'novo',
    google_maps_uri: 'https://maps.google.com/?cid=321654987',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'mock-place-5',
    place_id: 'mock-place-5',
    name: 'Academia Força & Movimento Fit',
    category: 'Academia',
    categories: ['gym', 'fitness_center'],
    address: 'R. Gaivota, 630 - Moema, São Paulo - SP',
    lat: -23.6033,
    lng: -46.6611,
    phone: '(11) 5051-2233',
    phone_e164: '+551150512233',
    is_mobile: false,
    has_whatsapp: false,
    has_site: true,
    website: 'https://movimentofit.com.br',
    rating: 4.5,
    reviews_count: 310,
    business_status: 'OPERATIONAL',
    status: 'OPERATIONAL',
    has_photos: true,
    score: 45,
    funil_status: 'novo',
    google_maps_uri: 'https://maps.google.com/?cid=741852963',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
